# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Superadmin
  admin_email: admin@progressor.com
  admin_password: admin123
  email_provider_username: jrizzle88888@gmail.com
  email_provider_password: blueboogers
  domain_name: progressorio.herokuapp.com
  secret_key_base: d95f6f0a0c7b40d0e25fb6b1054bb2cb7dbd2077b82730b0c196be7caecdb13a3bb99a4941c0ff9225588aeb30456d0025485e99e46e2e2700b26c9a17a05c64

test:
  domain_name: example.com
  secret_key_base: 203f8f54f6bc4db41a6ddc1d6bab293dce544d3f107953eee5f5b1b3d26eaa0d66baf4d182f998d100f413504fdb0d02b59b3c05c3c2d5837df767393db735c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: admin@progressor.com
  admin_password: admin123
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: progressorio.herokuapp.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
